stages:
  - install_opam_coqc
  - preliminaires
  - install_solc
  - install_sct
  - translating
  - .post

before_script:
  - cat /etc/os-release

opam-coq-job:
  stage: install_opam_coqc
  script:
    - cmake -version
    - if eval opam switch create alt 4.11.2; then eval echo ok; else eval opam switch alt; fi
    - opam switch alt
    - eval $(opam env)
    - opam pin add coq 8.15.2 -y
    - echo ok

mkdir-job:
  stage: preliminaires
  script:
  - if mkdir container_dir; then echo "container_dir created"; fi

solc-job:
  stage: install_solc
  script:
    - cd container_dir
    - git clone git@github.com:tonlabs/TON-Solidity-Compiler.git
    - cd TON-Solidity-Compiler
    - sh ./compiler/scripts/install_deps.sh
    - mkdir build
    - cd build
    - cmake ../compiler/ -DCMAKE_BUILD_TYPE=Release
    - cmake --build . -- -j8
    - cd ../..
    - ls